[book]
authors = ["xi xiao"]
language = "en"
multilingual = false
src = "src"
title = "Personal blog - Xi Xiao"

[output.html]
git-repository-url = "https://github.com/xixiaofinland/blog"

# [output.html.playground]
# editable = true
