[book]
authors = ["xi xiao"]
language = "en"
src = "src"
title = "Personal blog - Xi Xiao"

[output.html]
git-repository-url = "https://github.com/xixiaofinland/blog"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

# [preprocessor.mermaid]
# command = "mdbook-mermaid"

